### ISSUE TITLE
NullPointerException when opening specific method graphs

### ISSUE THREAD

**Issue by mhecker** [HiWiGAns/GraphVonAnsicht#115]
Using the attached file [npe.zip](https://github.com/HiWiGAns/GraphVonAnsicht/files/1022101/npe.zip), i get a NPE when opening the `1 Entr` method-graph vom the callgraph.

```
gans.sh --in="./api/joana.api.test/out/joana.api.testdata.toy.simp.NestedWithException.passon.pdg.hierarchical.graphml"
14:23:51.011 DEBUG GraphMLHandler - Finished reading GML-File.
14:23:51.016 INFO  CallGraphBuilder - 14 MethodGraphs to build.
14:23:51.064 INFO  CallGraphBuilder - Building MethodGraphs took 48
14:23:51.066 INFO  CallGraphBuilder - Building CallGraphVertices took 2
14:23:51.066 INFO  CallGraphBuilder - Building CallEdges in MethodGraphs took 0
14:23:51.066 INFO  CallGraphBuilder - 104 callEdges to process.
14:23:51.069 INFO  CallGraphBuilder - Building interprocedural edges took 3
14:23:51.076 INFO  CallGraphBuilder - Setting interprocedural vertices took 7
14:23:51.087 INFO  CallGraphBuilder - Searching calloops vertices took 11
14:23:51.088 INFO  CallGraphBuilder - Building 15 joanaedges for calledges took 1
14:23:51.144 INFO  CycleRemover - CycleRemover.removeCycles():
14:23:51.146 INFO  LayerAssigner - LayerAssigner.assignLayers():
14:23:51.150 INFO  LayerAssigner - created 5 layers
14:23:51.150 INFO  CrossMinimizer - CrossMinimizer.minimizeCrossings():
14:23:51.151 INFO  CrossMinimizer - stop on Threshold: false
14:23:51.152 INFO  CrossMinimizer - threshold: 0.0010000000474974513
14:23:51.152 INFO  CrossMinimizer - max runs: 10
14:23:51.153 INFO  CrossMinimizer - created 0 dummy vertices
14:23:51.155 INFO  CrossMinimizer - optimize up
14:23:51.158 INFO  CrossMinimizer - optimize down
14:23:51.159 INFO  CrossMinimizer - optimize up
14:23:51.159 INFO  CrossMinimizer - optimize down
14:23:51.160 INFO  CrossMinimizer - optimize up
14:23:51.160 INFO  CrossMinimizer - optimize down
14:23:51.160 INFO  CrossMinimizer - optimize up
14:23:51.161 INFO  CrossMinimizer - optimize down
14:23:51.161 INFO  CrossMinimizer - optimize up
14:23:51.161 INFO  CrossMinimizer - optimize down
14:23:51.162 INFO  CrossMinimizer - optimize up
14:23:51.162 INFO  CrossMinimizer - optimize down
14:23:51.162 INFO  CrossMinimizer - optimize up
14:23:51.162 INFO  CrossMinimizer - optimize down
14:23:51.163 INFO  CrossMinimizer - optimize up
14:23:51.163 INFO  CrossMinimizer - optimize down
14:23:51.163 INFO  CrossMinimizer - optimize up
14:23:51.164 INFO  CrossMinimizer - optimize down
14:23:51.164 INFO  CrossMinimizer - optimize up
14:23:51.164 INFO  CrossMinimizer - optimize down
14:23:51.165 DEBUG CrossMinimizer - 10 runs
14:23:51.165 INFO  VertexPositioner - VertexPositioner.positionVertices():
14:23:51.172 DEBUG VertexPositioner - did 1 runs, last was overlapping: false
14:23:51.185 INFO  EdgeDrawer - EdgeDrawer.drawEdges():
14:23:51.205 INFO  SugiyamaLayoutAlgorithm - runs in 62ms
14:24:03.892 INFO  MethodGraphLayout - Graph before: Vertices: 66, Edges: 128
14:24:03.894 INFO  CycleRemover - CycleRemover.removeCycles():
14:24:03.894 INFO  LayerAssigner - LayerAssigner.assignLayers():
14:24:03.894 INFO  LayerAssigner - created 2 layers
14:24:03.894 INFO  CrossMinimizer - CrossMinimizer.minimizeCrossings():
14:24:03.895 INFO  CrossMinimizer - stop on Threshold: false
14:24:03.895 INFO  CrossMinimizer - threshold: 0.0010000000474974513
14:24:03.895 INFO  CrossMinimizer - max runs: 10
14:24:03.895 INFO  CrossMinimizer - created 0 dummy vertices
14:24:03.896 INFO  CrossMinimizer - optimize up
14:24:03.896 INFO  CrossMinimizer - optimize down
14:24:03.896 INFO  CrossMinimizer - optimize up
14:24:03.896 INFO  CrossMinimizer - optimize down
14:24:03.896 INFO  CrossMinimizer - optimize up
14:24:03.896 INFO  CrossMinimizer - optimize down
14:24:03.897 INFO  CrossMinimizer - optimize up
14:24:03.897 INFO  CrossMinimizer - optimize down
14:24:03.897 INFO  CrossMinimizer - optimize up
14:24:03.897 INFO  CrossMinimizer - optimize down
14:24:03.897 INFO  CrossMinimizer - optimize up
14:24:03.898 INFO  CrossMinimizer - optimize down
14:24:03.898 INFO  CrossMinimizer - optimize up
14:24:03.898 INFO  CrossMinimizer - optimize down
14:24:03.898 INFO  CrossMinimizer - optimize up
14:24:03.898 INFO  CrossMinimizer - optimize down
14:24:03.898 INFO  CrossMinimizer - optimize up
14:24:03.899 INFO  CrossMinimizer - optimize down
14:24:03.899 INFO  CrossMinimizer - optimize up
14:24:03.899 INFO  CrossMinimizer - optimize down
14:24:03.899 DEBUG CrossMinimizer - 10 runs
14:24:03.899 INFO  VertexPositioner - VertexPositioner.positionVertices():
14:24:03.900 DEBUG VertexPositioner - did 1 runs, last was overlapping: false
14:24:03.900 INFO  EdgeDrawer - EdgeDrawer.drawEdges():
14:24:03.901 INFO  SugiyamaLayoutAlgorithm - runs in 7ms
14:24:03.901 INFO  CycleRemover - CycleRemover.removeCycles():
14:24:03.902 INFO  LayerAssigner - LayerAssigner.assignLayers():
14:24:03.902 INFO  LayerAssigner - created 2 layers
14:24:03.902 INFO  CrossMinimizer - CrossMinimizer.minimizeCrossings():
14:24:03.902 INFO  CrossMinimizer - stop on Threshold: false
14:24:03.902 INFO  CrossMinimizer - threshold: 0.0010000000474974513
14:24:03.902 INFO  CrossMinimizer - max runs: 10
14:24:03.902 INFO  CrossMinimizer - created 0 dummy vertices
14:24:03.902 INFO  CrossMinimizer - optimize up
14:24:03.903 INFO  CrossMinimizer - optimize down
14:24:03.903 INFO  CrossMinimizer - optimize up
14:24:03.903 INFO  CrossMinimizer - optimize down
14:24:03.903 INFO  CrossMinimizer - optimize up
14:24:03.903 INFO  CrossMinimizer - optimize down
14:24:03.903 INFO  CrossMinimizer - optimize up
14:24:03.903 INFO  CrossMinimizer - optimize down
14:24:03.903 INFO  CrossMinimizer - optimize up
14:24:03.904 INFO  CrossMinimizer - optimize down
14:24:03.904 INFO  CrossMinimizer - optimize up
14:24:03.904 INFO  CrossMinimizer - optimize down
14:24:03.904 INFO  CrossMinimizer - optimize up
14:24:03.904 INFO  CrossMinimizer - optimize down
14:24:03.904 INFO  CrossMinimizer - optimize up
14:24:03.904 INFO  CrossMinimizer - optimize down
14:24:03.905 INFO  CrossMinimizer - optimize up
14:24:03.905 INFO  CrossMinimizer - optimize down
14:24:03.905 INFO  CrossMinimizer - optimize up
14:24:03.905 INFO  CrossMinimizer - optimize down
14:24:03.905 DEBUG CrossMinimizer - 10 runs
14:24:03.905 INFO  VertexPositioner - VertexPositioner.positionVertices():
14:24:03.905 DEBUG VertexPositioner - did 1 runs, last was overlapping: false
14:24:03.906 INFO  EdgeDrawer - EdgeDrawer.drawEdges():
14:24:03.907 INFO  SugiyamaLayoutAlgorithm - runs in 6ms
14:24:03.910 INFO  LayerAssigner - relative Layer Constraint added
14:24:03.910 INFO  LayerAssigner - [RelativeLayerConstraint{top=[16[887]], bottom=[317[900], 18[873], 19[891], 17[911]], exact=true, distance=1}, RelativeLayerConstraint{top=[34[922]], bottom=[38[928], 289[915], 36[931], 322[916], 320[886], 321[904], 35[875], 290[909], 319[925], 37[927]], exact=true, distance=1}, RelativeLayerConstraint{top=[41[890]], bottom=[43[917], 291[901], 42[870], 292[919]], exact=true, distance=1}, RelativeLayerConstraint{top=[24[902]], bottom=[318[896], 26[866], 27[903], 25[923]], exact=true, distance=1}, RelativeLayerConstraint{top=[9[926]], bottom=[11[881], 10[908]], exact=true, distance=1}, RelativeLayerConstraint{top=[28[913]], bottom=[29[898], 31[868], 30[924]], exact=true, distance=1}, RelativeLayerConstraint{top=[12[877]], bottom=[15[920], 14[876], 13[894]], exact=true, distance=1}, RelativeLayerConstraint{top=[20[878]], bottom=[23[929], 21[905], 22[921]], exact=true, distance=1}]
14:24:03.910 INFO  LayerAssigner - absolute Layer Constraint added
14:24:03.911 INFO  LayerAssigner - [AbsoluteLayerConstraint{, vertices=[1[889]], layer=0}, AbsoluteLayerConstraint{, vertices=[316[897], 45[899], 268[884], 4[918], 267[893], 3[895]], layer=1}]
14:24:03.911 INFO  LayerAssigner - absolute Layer Constraint added
14:24:03.911 INFO  LayerAssigner - [LayerContainsOnlyConstraint{vertices=[1[889]], Layer=0}, LayerContainsOnlyConstraint{vertices=[316[897], 45[899], 268[884], 4[918], 267[893], 3[895]], Layer=1}]
14:24:03.912 INFO  CycleRemover - CycleRemover.removeCycles():
14:24:03.916 INFO  LayerAssigner - LayerAssigner.assignLayers():
14:24:03.920 INFO  LayerAssigner - created 8 layers
14:24:03.920 INFO  CrossMinimizer - CrossMinimizer.minimizeCrossings():
14:24:03.920 INFO  CrossMinimizer - stop on Threshold: false
14:24:03.920 INFO  CrossMinimizer - threshold: 0.0010000000474974513
14:24:03.920 INFO  CrossMinimizer - max runs: 10
14:24:03.924 INFO  CrossMinimizer - created 83 dummy vertices
14:24:03.925 INFO  CrossMinimizer - optimize up
14:24:03.926 INFO  CrossMinimizer - optimize down
14:24:03.926 INFO  CrossMinimizer - optimize up
14:24:03.927 INFO  CrossMinimizer - optimize down
14:24:03.928 INFO  CrossMinimizer - optimize up
14:24:03.928 INFO  CrossMinimizer - optimize down
14:24:03.929 INFO  CrossMinimizer - optimize up
14:24:03.929 INFO  CrossMinimizer - optimize down
14:24:03.930 INFO  CrossMinimizer - optimize up
14:24:03.930 INFO  CrossMinimizer - optimize down
14:24:03.931 INFO  CrossMinimizer - optimize up
14:24:03.931 INFO  CrossMinimizer - optimize down
14:24:03.932 INFO  CrossMinimizer - optimize up
14:24:03.932 INFO  CrossMinimizer - optimize down
14:24:03.933 INFO  CrossMinimizer - optimize up
14:24:03.933 INFO  CrossMinimizer - optimize down
14:24:03.934 INFO  CrossMinimizer - optimize up
14:24:03.934 INFO  CrossMinimizer - optimize down
14:24:03.935 INFO  CrossMinimizer - optimize up
14:24:03.935 INFO  CrossMinimizer - optimize down
14:24:03.935 DEBUG CrossMinimizer - 10 runs
14:24:03.936 INFO  VertexPositioner - VertexPositioner.positionVertices():
14:24:03.941 DEBUG VertexPositioner - did 2 runs, last was overlapping: false
14:24:03.959 INFO  EdgeDrawer - EdgeDrawer.drawEdges():
14:24:03.975 INFO  SugiyamaLayoutAlgorithm - runs in 63ms
14:24:03.976 INFO  MethodGraphLayout - Graph after: Vertices: 64, Edges: 124
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.assignCoordinatesToDummiesOnLayer(MethodGraphLayout.java:317)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.drawEdgesNew(MethodGraphLayout.java:250)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.lambda$layout$0(MethodGraphLayout.java:123)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:123)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:48)
	at edu.kit.student.joana.methodgraph.MethodGraphLayoutOption.applyLayout(MethodGraphLayoutOption.java:41)
	at edu.kit.student.gui.GAnsApplication.openGraph(GAnsApplication.java:610)
	at edu.kit.student.gui.GAnsApplication.openGraph(GAnsApplication.java:600)
	at edu.kit.student.gui.GAnsMediator.openGraph(GAnsMediator.java:28)
	at edu.kit.student.gui.GraphView.lambda$null$0(GraphView.java:148)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at edu.kit.student.gui.GraphViewSelectionController$SelectionGestures$3.handle(GraphViewSelectionController.java:209)
	at edu.kit.student.gui.GraphViewSelectionController$SelectionGestures$3.handle(GraphViewSelectionController.java:199)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jonas-Meier** [comment]
Fixed in 16aa612167ca2bfb658b46fdb68fc308991ff24e
